### PR TITLE
Modernize by replacing foreach with ranged-for

### PR DESCRIPTION
**Pull request by KonstantinRitt**

### CODE REVIEW

**Comment by nathan-osman** [comment]
Thanks so much for doing this. The only issue I foresee with merging this is that `qAsConst()` requires at least Qt 5.7 (the current minimum required version is 5.4). What are your thoughts on raising the minimum version to 5.7?

**Comment by KonstantinRitt** [comment]
qAsConst is merely an optimization and could be dropped if you prefer to stick to an ancient version of Qt. I, personally, do not see a reason to support anything older than 5.9 LTS.

**Comment by nathan-osman** [comment]
My only concern is that older Ubuntu LTS releases that are still within their active support timeline aren't able to provide newer releases (the newest version Ubuntu 16.04 LTS offers through xenial-updates is Qt 5.5).

But after thinking about it for a bit, I agree that it is probably best to raise the minimum supported version to at least 5.9. Earlier versions of this library can still be used and there are no outstanding bugs / security issues.

Thanks again for the pull request! I'll push a commit that raises the minimum version in `CMakeLists.txt`.

**Comment by KonstantinRitt** [comment]
Sorry for typos (I didn't run tests)

**Pull request merged**
